FroSidanMVC/Models/Entities/Product.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace FroSidanMVC.Models.Entities
{
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public decimal? TempPrice { get; set; }
        public int Balance { get; set; }
        public string ImgRef { get; set; }
        public string ThumbRef { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public int Quantity { get; set; }
    }
}

FroSidanMVC/Models/ViewModels/Products/CheckoutConfirmedVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FroSidanMVC.Models.ViewModels.Products
{
    public class CheckoutConfirmedVM
    {
        public string OrderID { get; set; }
    }
}

FroSidanMVC/Models/ViewModels/Products/CheckoutVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FroSidanMVC.Models.ViewModels.Products
{
    public class CheckoutVM
    {
        public string Id { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string Street { get; set; }
        [Required]
        public string Zip { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        public SummaryVM[] OrderCart { get; set; }
    }
}

FroSidanMVC/Models/ViewModels/Products/DetailVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FroSidanMVC.Models.ViewModels.Products
{
    public class DetailVM
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public decimal Price { get; set; }
    }
}

FroSidanMVC/Models/ViewModels/Products/IndexVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FroSidanMVC.Models.ViewModels.Products
{
    public class IndexVM
    {
        public string SubCategory { get; set; }
        public string Category { get; set; }

    }
}

FroSidanMVC/Models/ViewModels/Products/ShopVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FroSidanMVC.Models.ViewModels.Products
{
    public class ShopVM
    {
        public int Id { get; set; }
        public string SubCategory { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }

        public string ThumbnailUrl { get; set; }

       


    }
}

FroSidanMVC/Models/ViewModels/Products/SummaryVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FroSidanMVC.Models.ViewModels.Products
{
    public class SummaryVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public decimal? TempPrice { get; set; }
        public int Quantity { get; set; }
    }
}

FroSidanMVC/Controllers/MembersController.cs
using FroSidanMVC.Models;
using FroSidanMVC.Models.ViewModels.Members;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FroSidanMVC.Controllers
{
    public class MembersController : Controller
    {
        MembersService mService;
        private readonly ProductsService pService;

        public MembersController(MembersService mService, ProductsService pService)
        {
            this.mService = mService;
            this.pService = pService;
        }

        [Authorize]
        [HttpGet]
        [Route("MyPages")]
        public IActionResult MyPagesAsync()
        {
            var orders = mService.GetOrdersAsync();

            return View(new MyPagesVM { Username = User.Identity.Name, Orders = orders });
        }

        [Authorize]
        [HttpGet]
        [Route("MyOrder/{orderID}")]
        public async Task<IActionResult> MyOrderAsync(int orderID)
        {
            var shoppingCartJSON = pService.GetShoppingCartFromOrder(orderID);
            List<int> shoppingCart = JsonConvert.DeserializeObject<List<int>>(shoppingCartJSON);
            var orders = await pService.GetSummaryVMAsync(shoppingCart);

            MyOrderLineVM[] model = orders.Select(x => new MyOrderLineVM
            {
                Id = x.Id,
                Name = x.Name,
                OrderId = orderID,
                Price = x.Price,
                Quantity = x.Quantity,
                Status = "Under behandling",
            })
                .ToArray();
            return View(model);
        }

        [AllowAnonymous]
        [HttpGet]
        [Route("login")]
        public IActionResult Login(string returnUrl)
        {
            if (returnUrl == null)
                returnUrl = "MyPages";

            return View(new MembersLoginVM { ReturnUrl = returnUrl });

        }
        [HttpPost]
        [Route("login")]
        public async Task<IActionResult> LoginAsync(MembersLoginVM viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            // Check if credentials is valid (and set auth cookie)
            var success = await mService.TryLoginAsync(viewModel);
            if (!success)
            {
                // Show error
                ModelState.AddModelError(nameof(MembersLoginVM.Username), "Login failed");
                return View(viewModel);
            }

            // Redirect user
            if (string.IsNullOrWhiteSpace(viewModel.ReturnUrl))
                return RedirectToAction(nameof(MyPagesAsync));
            else
                return Redirect(viewModel.ReturnUrl);
        }

        [HttpGet]
        [Route("register")]
        public IActionResult Register()
        {
            return View();
        }

        [Route("register")]
        [HttpPost]
        public async Task<IActionResult> RegisterAsync(MemberRegisterVM vM)
        {
            if (!ModelState.IsValid)
                return View(vM);

            // Try to register user
            var success = await mService.TryRegisterAsync(vM);
            if (!success)
            {
                // if not succesful, Show error
                ModelState.AddModelError(string.Empty, "Misslyckades att skapa konto");
                return View(vM);
            }

            // if succesful, redirect user
            return RedirectToAction(nameof(Login));
        }

        [HttpGet]
        [Route("logout")]
        public async Task<IActionResult> LogoutAsync()
        {
            await mService.SignOutAsync();
            return RedirectToAction(nameof(Login));
        }

    }
}

FroSidanMVC/Controllers/ProductsController.cs
using FroSidanMVC.Models;
using FroSidanMVC.Models.ViewModels.Products;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Http;
using FroSidanMVC.Models.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http.Extensions;
using FroSidanMVC.Views.Shared.Components;
using Newtonsoft.Json;

namespace FroSidanMVC.Controls
{
    public class ProductsController : Controller
    {
        public ProductsService pService;
        private readonly MembersService mService;

        public ProductsController(ProductsService pService, MembersService mService)
        {
            this.pService = pService;
            this.mService = mService;
        }

        [Route("")]
        [Route("products/index")]
        [Route("Index")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("products/{id}")]
        public async Task<IActionResult> DetailAsync(int id)
        {
            var product = await pService.GetProductDetailVMAsync(id);
            return View(product);
        }

        [Route("Shop")]
        [Route("products/shop")]
        [HttpGet]
        public IActionResult Shop(string category, string subcategory, string sortBy)
        {
            if (subcategory == null && category == null)
            {
                var allProducts = pService.GetAllProductsAndSort(sortBy);
                return View(allProducts);
            }
            else if (subcategory == null)
            {
                var productsByCategory = pService.GetProductsByCategory(category, sortBy);
                return View(productsByCategory);
            }
            else
            {
                var productsBySubCategory = pService.GetProductsBySubCategory(subcategory, sortBy);
                return View(productsBySubCategory);
            }
        }
        [HttpGet]
        [Route("AddToCartCheckout/{id}")]

        public async Task<IActionResult> AddToCartCheckoutAsync(int id)
        {
            var shoppingCart = await pService.AddToCartAsync(id);
            var model = await pService.GetSummaryVMAsync(shoppingCart);
            return PartialView("_OrderSummary", model);
        }

        [HttpGet]
        [Route("AddToCartShop/{id}")]

        public async Task<IActionResult> AddToCartShopAsync(int id)
        {
            var shoppingCart = await pService.AddToCartAsync(id);
            return ViewComponent("ShoppingcartComponent", shoppingCart);
        }

        [HttpGet]
        [Route("ClearCart")]

        public IActionResult ClearCart()
        {
            pService.DeleteCart();
            return Content(pService.GetShoppingCart().Count().ToString()); // Vad är en lämplig return???
        }
        [HttpGet]
        [Route("RemoveSingleFromCart/{id}")]

        public async Task<IActionResult> RemoveSingleFromCartAsync(int id)
        {

            var shoppingCart = pService.RemoveSingleFromCart(id);

            var model = await pService.GetSummaryVMAsync(shoppingCart);

            return PartialView("_OrderSummary", model);
        }

        [HttpGet]
        [Route("RemoveAllFromCart/{id}")]

        public async Task<IActionResult> RemoveAllFromCartAsync(int id)
        {
            var shoppingCart = pService.RemoveAllFromCart(id);
            var model = await pService.GetSummaryVMAsync(shoppingCart);
            return PartialView("_OrderSummary", model);
        }

        [Route("Checkout")]
        [HttpGet]
        public async Task<IActionResult> CheckoutAsync()
        {
            var User = await mService.GetUser();
            CheckoutVM input;

            if (User != null)
            {
                input = new CheckoutVM
                {
                    Id = User.Id,
                    FirstName = User.FirstName,
                    LastName = User.LastName,
                    Email = User.Email,
                    Street = User.Street,
                    Zip = User.Zip,
                    City = User.City,
                    OrderCart = await pService.GetSummaryVMAsync()
                };
            }
            else
            {
                input = new CheckoutVM
                {
                    OrderCart = await pService.GetSummaryVMAsync()
                };
            };

            return View(input);
        }
        [Route("Checkout")]
        [HttpPost]
        public async Task<IActionResult> CheckoutAsync(CheckoutVM input)
        {
            int orderNum = await pService.PlaceOrderAsync(input);
            pService.DeleteCart();
            TempData["Message"] = $"{orderNum}";


            return RedirectToAction(nameof(CheckoutConfirmed));
        }
        [Route("CheckoutConfirmed")]
        [HttpGet]
        public IActionResult CheckoutConfirmed()
        {
            string ID = ((string)TempData["Message"]);
            CheckoutConfirmedVM input = new CheckoutConfirmedVM
            {
                OrderID = ID
            };
            return View(input);
        }

        [HttpGet]
        [Route("Search/{searchStr}")]

        public IActionResult Search(string searchStr)
        {

            var products = pService.GetAllProducts();
            var words = searchStr.Split(' ');

            foreach (string search in words)
            {
                products = products
                    .Where(x => x.Name.ToLower().Contains(search.ToLower()) || x.SubCategory.ToLower().Contains(search.ToLower()))
                    .ToArray();
            }

            return PartialView("_ShopProducts", products);
        }
    }
}

FroSidanMVC/Views/Products/Checkout.cshtml
@model CheckoutVM
@{ViewBag.HideCart = true;}
<div id="partial">
    <partial name="_OrderSummary" model="Model.OrderCart" />
</div>

@{
    if (Model.Email == null)
    {<p style="padding-left:30px">Du är inte inloggad. Vill du <text><strong style="color:blue"><a asp-controller="Members" asp-action="Login" asp-route-returnUrl="Checkout">logga in</a></strong></text>?</p>}
}

@if (Model.OrderCart.Length != 0)
{

    <form asp-controller="Products" asp-action="Checkout" style="padding-left:30px">
        <h4>Adress för leverans</h4>
        <table>
            <tr>
                <td><label asp-for="FirstName">Förnamn: </label></td>
                <td><input asp-for="FirstName" /></td>
                <td><span asp-validation-for="FirstName"></span></td>
            </tr>
            <tr>
                <td><label asp-for="LastName">Efternamn: </label></td>
                <td><input asp-for="LastName" /></td>
                <td><span asp-validation-for="LastName"></span></td>
            </tr>
            <tr>
                <td><label asp-for="Street">Gata: </label></td>
                <td><input asp-for="Street" /></td>
                <td><span asp-validation-for="Street"></span></td>
            </tr>
            <tr>
                <td><label asp-for="Zip">Postnummer: </label></td>
                <td><input asp-for="Zip" /></td>
                <td><span asp-validation-for="Zip"></span></td>
            </tr>
            <tr>
                <td><label asp-for="City">Stad: </label></td>
                <td><input asp-for="City" /></td>
                <td><span asp-validation-for="City"></span></td>
            </tr>
            <tr>
                <td><label asp-for="Email">E-mail</label></td>
                <td><input asp-for="Email" /></td>
                <td><span asp-validation-for="Email"></span></td>
            </tr>

        </table>
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="OrderCart" />

        <br />
        <br />

        <h4>Betalningsalternativ</h4>

        <div class="form-check">
            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
            <label class="form-check-label" for="exampleRadios1">
                Kort (Visa/Master Card/American Express)
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
            <label class="form-check-label" for="exampleRadios2">
                Faktura
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios3" value="option3">
            <label class="form-check-label" for="exampleRadios3">
                Klarna
            </label>
        </div>
        <input type="submit" value="Lägg order" data-bs-toggle="modal" data-bs-target="#checkoutModal" />
        <br />

    </form>
    <br />
    <br />
}

@section scripts
{
    <script type="text/javascript">
        function AddToCartCheckout(id) {
            $.ajax({
                url: "/AddToCartCheckout/" + id,
                type: "GET",
                success: (result) => $("#partial").html(result)
            });
        };

        function RemoveAllFromCart(id) {
            $.ajax({
                url: "/RemoveAllFromCart/" + id,
                type: "GET",
                success: (result) => $("#partial").html(result)
            });
        };

        function RemoveSingleFromCart(id) {
            $.ajax({
                url: "/RemoveSingleFromCart/" + id,
                type: "GET",
                success: (result) => $("#partial").html(result)
            });
        };
    </script>
}

FroSidanMVC/Views/Products/CheckoutConfirmed.cshtml
@model CheckoutConfirmedVM

    <div style="padding-left:30px">

        <h3>Beställning slutförd</h3>
        <p>Tack för din beställning. Din order behandlas och beräknas vara levererad inom 1-3 vardagar.</p>
        <p>Ditt ordernummer är: <strong>@Model.OrderID</strong></p>
        <a asp-controller="Members" asp-action="Mypages">Gå till <strong>mina sidor</strong>.</a>
</div>

FroSidanMVC/Views/Products/Detail.cshtml
@model DetailVM


<div class=".container-lg" style="
    width: 30rem;
    margin-left: auto;
    margin-right: auto;
    margin-top: 50px">
    <div class="card-img-top">
        <img src="/Images/@Model.Url" class="card-img-top" alt="Produktbild">
        <br />
        <h3>@Model.ProductName</h3>
    </div>
    <div>
        <br />
        <br />
        <p class="card-text">@Model.Description</p>
        <h6>@Model.Price.ToString("c")</h6><a onclick="AddToCart(@Model.Id)"  class="btn btn-primary">Lägg i varukorg <i class="fas fa-shopping-cart"></i></a>
    </div>
</div>




@section scripts
{
    <script type="text/javascript">
        function AddToCart(id) {
            $.ajax({
                url: "/AddToCartShop/" + id,
                type: "GET",
                success: (result) => $("#component").html(result)
            });
        };
    </script>
}

FroSidanMVC/Views/Products/Index.cshtml
@{ViewBag.Title = "Startsida";}

@*<h1 id="h1Index">Välkommen till Fröbutiken</h1>*@



<div class="rowIndex">
    <div class="col-6">
        <div class="cardIndex text-black" style="width: 600px">
            <a asp-controller="Products" asp-action="Shop" asp-route-category="seeds">
                <img src="~/Images/Seeds_Logo.jpg" height="200" width="600" class="card-img" alt="Kategori fröer">
            </a>
        </div>
    </div>
</div>
<div class="rowIndex">
    <div class="col-6">
        <div class="cardIndex text-black" style="width: 600px">
            <a asp-controller="Products" asp-action="Shop" asp-route-category="lamps">
                <img src="~/Images/Lampor_logo.jpg" height="200" width="600" class="card-img" alt="Kategori fröer">
            </a>
        </div>
    </div>
</div>
<div class="rowIndex" style="padding-bottom: 30px;">
    <div class="col-6">
        <div class="cardIndex text-black" style="width: 600px">
            <a asp-controller="Products" asp-action="Shop" asp-route-category="accessories">
                <img src="~/Images/Acc_logo.jpg" height="200" width="600" class="card-img" alt="Kategori fröer">
            </a>
        </div>
    </div>
</div>

@*<div class="row">
    <div class="col col-sm-6 col-md-4 col-lg-2 col-xl-2">
        <div class="card text-black" style="width: 200px">
            <a asp-controller="Products" asp-action="Shop" asp-route-category="seeds" asp-route-subcategory="chili">
                <img src="~/Images/chilipic.jpg" height="200" width="200" class="card-img" alt="Bild på fröpåsar">
            </a>
        </div>
    </div>
    <div class="col col-sm-12 col-md-6 col-lg-2 col-xl-2">
        <div class="card text-black" style="width: 200px">
            <a asp-controller="Products" asp-action="Shop" asp-route-category="seeds" asp-route-subcategory="tomato">
                <img src="~/Images/tomatopic.jpg" height="200" width="200" class="card-img" alt="Bild på fröpåsar">
            </a>
        </div>
    </div>
    <div class="col col-sm-12 col-md-6 col-lg-2 col-xl-2">
        <div class="card text-black" style="width: 200px">
            <a asp-controller="Products" asp-action="Shop" asp-route-category="seeds" asp-route-subcategory="squash">
                <img src="~/Images/pumpasquash.jpg" height="200" width="200" class="card-img" alt="Bild på fröpåsar">
            </a>
        </div>
    </div>

</div>
<div class="row">
    <div class="col-2">
        <div class="card text-black">
            <a asp-controller="Products" asp-action="Shop" asp-route-category="seeds" asp-route-subcategory="chili">
                <img src="~/Images/chilipic.jpg" height="200px" class="card-img" alt="Bild på fröpåsar">
            </a>
            <div class="card-img-overlay">
                <h1 class="card-title">Chili</h1>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="card text-black">
            <a asp-controller="Products" asp-action="Shop" asp-route-category="seeds" asp-route-subcategory="tomato">
                <img src="~/Images/tomatopic.jpg" height="200px" class="card-img" alt="Bild på fröpåsar">
            </a>
            <div class="card-img-overlay">
                <h1 class="card-title">Tomater</h1>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="card text-black">
            <a asp-controller="Products" asp-action="Shop" asp-route-category="seeds" asp-route-subcategory="squash">
                <img src="~/Images/pumpasquash.jpg" height="200px" class="card-img" alt="Bild på fröpåsar">
            </a>
            <div class="card-img-overlay">
                <h1 class="card-title">Pumpa och squash</h1>
            </div>
        </div>
    </div>
</div>

<br />
<div class="row">
    <div class="col-6">
        <div class="card text-black">
            <a asp-controller="Products" asp-action="Shop" asp-route-category="lampor">
                <img src="~/Images/lights.jpg" class="im-fluid" height="200px" class="card-img" alt="Bild på lampor">
            </a>
            <div class="card-img-overlay">
                <h1 class="card-title">Lampor</h1>
            </div>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-6">
        <div class="card text-black">
            <a asp-controller="Products" asp-action="Shop" asp-route-category="accessories">
                <img src="~/Images/odlingstillbehor.jpg" class="im-fluid" height="200px" class="card-img" alt="Bild på lampor">
            </a>
            <div class="card-img-overlay">
                <h1 class="card-title">Odlingstillbehör</h1>
            </div>
        </div>
    </div>
</div>*@

FroSidanMVC/Views/Products/Shop.cshtml
@model ShopVM[]
@{ViewBag.Title = "Shop";}

<div class="side-menu">
    <form id="searchForm">
        <input type="text" id="searchStr" />
        <input type="submit" value="Sök" />
    </form>
    <ul>
        <li class="nav-item dropdown" style="font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Sortera efter
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="/products/shop?category=@Context.Request.Query["category"]&subcategory=@Context.Request.Query["subcategory"]&sortBy=recommeded">Rekommenderat</a>
                <a class="dropdown-item" href="/products/shop?category=@Context.Request.Query["category"]&subcategory=@Context.Request.Query["subcategory"]&sortBy=price">Pris</a>
                <a class="dropdown-item" href="/products/shop?category=@Context.Request.Query["category"]&subcategory=@Context.Request.Query["subcategory"]&sortBy=name">Namn</a>
            </div>
        </li>

    </ul>
    <nav class="leftnav">
        <hr />
        <p style="padding-left: 10px;">Frösorter</p>
        <a asp-controller="Products" asp-action="Shop" asp-route-category="seeds"><i class="fas fa-seedling"></i>Bläddra alla frön</a>
        <a asp-controller="Products" asp-action="Shop" asp-route-category="seeds" asp-route-subcategory="chili"><i class="fas fa-pepper-hot"></i>Chili</a>
        <a asp-controller="Products" asp-action="Shop" asp-route-category="seeds" asp-route-subcategory="tomato"><i class="fas fa-leaf"></i>Tomater</a>
        <a asp-controller="Products" asp-action="Shop" asp-route-category="seeds" asp-route-subcategory="squash"><i class="fas fa-tree"></i>Squash och Pumpa</a>
        <hr />
        <p style="padding-left: 10px;">Tillbehör</p>
        <a asp-controller="Products" asp-action="Shop" asp-route-category="lamps"><i class="fas fa-lightbulb"></i>Lampor</a>
        <a asp-controller="Products" asp-action="Shop" asp-route-category="accessories"><i class="fas fa-hammer"></i>Övriga tillbehör</a>
    </nav>
    <ul>
        <li class="nav-item">
            <a class="nav-link active" asp-controller="Products" asp-action="Shop">Rensa filter</a>
        </li>
    </ul>
</div>


<div id="partial">
    <partial name="_ShopProducts" model="Model" />
</div>


@section scripts
{
    <script type="text/javascript">
        function AddToCart(id) {
            console.log("före ajax");
            $.ajax({
                url: "/AddToCartShop/" + id,
                type: "GET",
                success: (result) => $("#component").html(result)
            });
            let x = document.getElementById(id+'button');
            x.style.color = "blue";
            console.log("efter ajax");
        };

        $("#searchForm").submit(function (e) {
            e.preventDefault();
            search = searchStr.value;
            $.ajax({
                url: "/Search/" + search,
                type: "GET",
                success: (result) => $("#partial").html(result)
            });
        });
    </script>

}